# Generated by herdr-tsk scripts/release.py. Commit to homebrew-tap/Formula/tsk.rb.
class Tsk < Formula
  desc "Terminal task board for you and your agents"
  homepage "https://gettsk.sh"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/smarzban/herdr-tsk/releases/download/v0.10.0/tsk-v0.10.0-aarch64-apple-darwin.tar.gz"
      sha256 "c0fef12fa3d7ab365e88dc38439413f236b61ec4b8de59e051180eb6abab07a0"
    end
    on_intel do
      url "https://github.com/smarzban/herdr-tsk/releases/download/v0.10.0/tsk-v0.10.0-x86_64-apple-darwin.tar.gz"
      sha256 "1f524bbb6c6ad0236c6b4e9d49802a4140bc2129f5ea7c8459ec06ceb4650fd5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/smarzban/herdr-tsk/releases/download/v0.10.0/tsk-v0.10.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "5bdf65ee195744da6c560b57ba322d731552026354fa051744cbd224ba4dff91"
    end
    on_intel do
      url "https://github.com/smarzban/herdr-tsk/releases/download/v0.10.0/tsk-v0.10.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "aa6f52db3379b34e29f5ea2628476abd1171c6203e4ced2398a6ee390b52dd9b"
    end
  end

  def install
    bin.install "tsk"
  end

  def caveats
    <<~EOS
      Homebrew installs are noninteractive. To register the shared tsk binary and shortcuts in Herdr, run:
        tsk setup herdr
      To add the tsk skill to your coding agents, run:
        tsk setup agents
    EOS
  end

  test do
    ENV["TSK_STATE_DIR"] = (testpath/"state").to_s
    ENV["TSK_CONFIG_DIR"] = (testpath/"config").to_s
    assert_match "usage: tsk", shell_output("#{bin}/tsk --help")
    system bin/"tsk", "add", "--desk", "-t", "Homebrew smoke"
    assert_match "Homebrew smoke", shell_output("#{bin}/tsk list --desk")
  end
end
