# Generated by herdr-tsk scripts/release.py. Commit to homebrew-tap/Formula/tsk.rb.
class Tsk < Formula
  desc "Terminal task board for you and your agents"
  homepage "https://gettsk.sh"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/smarzban/herdr-tsk/releases/download/v0.8.2/tsk-v0.8.2-aarch64-apple-darwin.tar.gz"
      sha256 "965913463a1726834b2dbe79401f5174a53e2e8b63328e59a11c60b2ef4f712e"
    end
    on_intel do
      url "https://github.com/smarzban/herdr-tsk/releases/download/v0.8.2/tsk-v0.8.2-x86_64-apple-darwin.tar.gz"
      sha256 "b18c6025403828b6bce905dd0c10db4a12a901fa5edb24396c169a75cb338a34"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/smarzban/herdr-tsk/releases/download/v0.8.2/tsk-v0.8.2-aarch64-unknown-linux-musl.tar.gz"
      sha256 "5b70d5a7760673fbb02f77d23c345d5d5cf51dcc74845d2afa277a91691317cf"
    end
    on_intel do
      url "https://github.com/smarzban/herdr-tsk/releases/download/v0.8.2/tsk-v0.8.2-x86_64-unknown-linux-musl.tar.gz"
      sha256 "e2998269a071e502256a46b81720cbc8dda8f04053bdb77e4753e91bfc659960"
    end
  end

  def install
    bin.install "tsk"
  end

  def caveats
    <<~EOS
      Homebrew installs are noninteractive. To register the shared tsk binary and shortcuts in Herdr, run:
        tsk setup herdr
    EOS
  end

  test do
    ENV["TSK_STATE_DIR"] = (testpath/"state").to_s
    ENV["TSK_CONFIG_DIR"] = (testpath/"config").to_s
    assert_match "usage: tsk", shell_output("#{bin}/tsk --help")
    system bin/"tsk", "add", "--desk", "-t", "Homebrew smoke"
    assert_match "Homebrew smoke", shell_output("#{bin}/tsk list --desk")
  end
end
