# Generated by herdr-tsk scripts/release.py. Commit to homebrew-tap/Formula/tsk.rb.
class Tsk < Formula
  desc "Terminal task board for you and your agents"
  homepage "https://gettsk.sh"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/smarzban/herdr-tsk/releases/download/v0.9.0/tsk-v0.9.0-aarch64-apple-darwin.tar.gz"
      sha256 "2ecae9c36e0c974ef79d3131d8a6558017e078421f8d03408303ea771a95f1e4"
    end
    on_intel do
      url "https://github.com/smarzban/herdr-tsk/releases/download/v0.9.0/tsk-v0.9.0-x86_64-apple-darwin.tar.gz"
      sha256 "c2c465e3c4e6f9b3715c5037ec4f3a7c67f73f8e9a36c6282fe2d50eb9645666"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/smarzban/herdr-tsk/releases/download/v0.9.0/tsk-v0.9.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "4c93ac83e2fb7b293110ef8779d36d93bbb514050406fca0570b954487d492e2"
    end
    on_intel do
      url "https://github.com/smarzban/herdr-tsk/releases/download/v0.9.0/tsk-v0.9.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "00835d542082aea66899463ebfb5426b90e92110054fcb846ed66f342002f044"
    end
  end

  def install
    bin.install "tsk"
  end

  def caveats
    <<~EOS
      Homebrew installs are noninteractive. To register the shared tsk binary and shortcuts in Herdr, run:
        tsk setup herdr
      To add the tsk skill to your coding agents, run:
        tsk setup agents
    EOS
  end

  test do
    ENV["TSK_STATE_DIR"] = (testpath/"state").to_s
    ENV["TSK_CONFIG_DIR"] = (testpath/"config").to_s
    assert_match "usage: tsk", shell_output("#{bin}/tsk --help")
    system bin/"tsk", "add", "--desk", "-t", "Homebrew smoke"
    assert_match "Homebrew smoke", shell_output("#{bin}/tsk list --desk")
  end
end
